// SPDX-License-Identifier: MIT
// Entry point for published package consumers.
// Re-export schemaTypes and validation schemas.
export * from '../schemas';
export * from '../validation/productSchema';
export * from '../validation/orderSchema';
// Re-export generated Sanity document types if present (optional for consumers)
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - file generated by `npm run codegen`
export * from '../generated/sanity.types';
